server:
  port: 8011

spring:
  application:
    name: metering-digital-multimeter
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      maxFileSize: 5MB  #??????MB???(??B)
      maxRequestSize: 10MB
#  datasource:
#    url: jdbc:sqlserver://172.16.20.152:1433;database=metteam
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    password: 123456
#    username: admin

  datasource:
    url: jdbc:sqlserver://lbc.codyart.tech:21453;database=metteam
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: junjun+1993
    username: sa

# ??????
management:
  endpoints:
    web:
      exposure:
        include: '*'


# MyBatis
mybatis:
  # ???????
  typeAliasesPackage: com.metering
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/*Mapper.xml

# PageHelper????
pagehelper:
  helperDialect: sqlServer
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
